/* ================================================================
   abuse-types.js — DNS Abuse Type detail pages
   Click footer links → show detail page with back button
================================================================ */
'use strict';

const ABUSE_TYPES = {
  'malware': {
    tag:   'MALWARE / C2',
    color: 'var(--red)',
    icon:  '🦠',
    title: 'Malware & Command-and-Control Infrastructure',
    what: `Malware is malicious software distributed via DNS infrastructure to infect, 
control, or steal data from victim systems. Command-and-Control (C2) domains are 
the backbone of malware operations — infected machines "call home" to C2 servers 
to receive instructions, download payloads, or exfiltrate stolen data.`,
    howWorks: `Attackers register domains that act as communication hubs for malware campaigns. 
These domains often use fast-flux DNS (rapidly rotating IPs), bulletproof hosting, 
or Domain Generation Algorithms (DGA) to evade takedowns. Common malware families 
using C2 infrastructure include Emotet, Cobalt Strike, QakBot, IcedID, and ransomware operators.`,
    indicators: [
      'Domains resolving to multiple IPs in rapid succession (fast-flux)',
      'Newly registered domains with no web content but active DNS',
      'Domains matching known DGA patterns (random-looking names)',
      'Domains hosted on bulletproof ASNs or hosting providers',
      'SSL certificates issued minutes before first observed traffic',
      'Subdomains used as C2 beacon endpoints (e.g. a1b2c3.malware-domain.com)',
    ],
    report: `Submit the full domain and any associated IPs, observed beacon traffic, 
sandbox analysis reports, malware sample hashes, and network packet captures. 
Include first/last seen dates and the malware family if identified.`,
    severity: 'CRITICAL',
  },

  'botnet': {
    tag:   'BOTNET INFRASTRUCTURE',
    color: 'var(--red)',
    icon:  '🤖',
    title: 'Botnet Infrastructure',
    what: `A botnet is a network of compromised computers (bots) controlled by an attacker 
via DNS-based command infrastructure. Botnets are used for DDoS attacks, spam 
distribution, credential theft, ransomware deployment, and cryptocurrency mining. 
DNS abuse enables botnet resilience through fast-flux and DGA techniques.`,
    howWorks: `Botnet operators register networks of domains that serve as C2 nodes. 
When one domain is taken down, bots automatically connect to the next available domain 
generated by the algorithm or resolved through the fast-flux network. 
Notable botnets include Mirai (IoT), Necurs (spam), TrickBot, and ZLoader.`,
    indicators: [
      'Hundreds of domains registered in bulk with similar WHOIS data',
      'Fast-flux DNS with TTL values of 60 seconds or less',
      'Domains sharing nameservers with known malicious infrastructure',
      'IP ranges associated with known bulletproof hosting providers',
      'Domains responding to HTTP/HTTPS on non-standard ports',
      'Traffic patterns showing regular beacon intervals from infected hosts',
    ],
    report: `Document the full domain cluster, associated IPs and ASNs, 
observed bot traffic patterns, registration data, and passive DNS history. 
Infrastructure correlation across multiple domains strengthens the report significantly.`,
    severity: 'CRITICAL',
  },

  'phishing': {
    tag:   'PHISHING',
    color: 'var(--warn)',
    icon:  '🎣',
    title: 'Phishing Domains',
    what: `Phishing is the fraudulent use of domains to impersonate legitimate organizations 
and deceive users into surrendering credentials, financial information, or personal data. 
DNS abuse enables phishing through typosquatting, homograph attacks, and lookalike domains 
that closely mimic trusted brands.`,
    howWorks: `Attackers register domains that visually resemble legitimate brands 
(e.g. "paypa1.com", "secure-bankname-login.com") and host credential harvesting pages. 
Phishing campaigns typically have short lifespans — domains are rotated every 24–72 hours 
to evade blocklists. Many use free SSL certificates to appear legitimate.`,
    indicators: [
      'Typosquatted domains (character substitution, addition, or omission)',
      'Domains containing brand names as subdomains (e.g. paypal.attacker.com)',
      'Homograph attacks using Unicode characters resembling Latin letters',
      'Newly registered domains with SSL certificates and login page content',
      'Domains hosted on shared hosting with multiple other phishing pages',
      'Redirect chains through multiple domains to final phishing page',
    ],
    report: `Include the full phishing URL, target brand being impersonated, 
screenshot of the phishing page, HTML source if available, and any email 
headers from the phishing lure. URLScan.io reports are particularly useful.`,
    severity: 'HIGH',
  },

  'pharming': {
    tag:   'PHARMING / DNS HIJACK',
    color: 'var(--warn)',
    icon:  '☠️',
    title: 'Pharming & DNS Hijacking',
    what: `Pharming is the manipulation of DNS resolution to redirect users from legitimate 
websites to fraudulent ones without their knowledge. Unlike phishing, pharming does not 
require user interaction with a malicious link — it poisons the DNS layer itself. 
Methods include router DNS hijacking, DNS cache poisoning, and BGP hijacking.`,
    howWorks: `Attackers compromise DNS resolvers, routers, or ISP infrastructure to redirect 
queries for legitimate domains to attacker-controlled servers. Victims type the correct URL 
but are silently redirected to a fake site. Pharming is particularly dangerous because 
standard browser security indicators (URL bar) appear correct to the victim.`,
    indicators: [
      'DNS responses returning unexpected IP addresses for known-good domains',
      'Router DNS settings changed to attacker-controlled resolvers',
      'ISP-level DNS responses inconsistent with authoritative nameservers',
      'SSL certificate mismatch warnings for previously trusted sites',
      'Multiple users at same network location experiencing identical redirects',
      'BGP route hijacking causing traffic interception at network level',
    ],
    report: `Document the affected domain, expected IP vs. observed IP, 
DNS resolver returning incorrect results, network location (ISP, ASN), 
and timestamps. Packet captures showing DNS response manipulation are essential.`,
    severity: 'HIGH',
  },

  'snowshoe': {
    tag:   'SNOWSHOE SPAM',
    color: 'var(--accent)',
    icon:  '📧',
    title: 'Snowshoe Spam',
    what: `Snowshoe spam is a technique where spam is distributed across a large number 
of domains and IP addresses to minimize the volume per sending point, thereby evading 
reputation-based filters. The analogy is snowshoes distributing weight across a wide surface. 
When used to distribute malware, phishing links, or fraudulent content, it constitutes DNS abuse.`,
    howWorks: `Operators register hundreds or thousands of domains and IP addresses, 
sending a small volume of spam from each to stay below detection thresholds. 
Despite low per-domain volume, the aggregate campaign can deliver millions of messages. 
WHOIS data often links all domains to a single registrant through shared registration 
details, billing information, or nameserver patterns.`,
    indicators: [
      'Large numbers of domains registered in bulk with similar WHOIS data',
      'Shared nameservers, registrant email, or billing address across domains',
      'Low message volume per sending IP but high aggregate volume',
      'Domains used briefly then abandoned (high churn rate)',
      'Sending IPs distributed across multiple ASNs and geographies',
      'Message content linking to malware, phishing, or fraud domains',
    ],
    report: `Document the sending domains, associated IPs, shared WHOIS data linking 
the campaign, message samples, and aggregate volume data. WHOIS history correlation 
across the domain cluster is the strongest evidence for this abuse type.`,
    severity: 'MEDIUM',
  },

  'dga': {
    tag:   'DGA / FAST-FLUX',
    color: 'var(--accent)',
    icon:  '⚙️',
    title: 'Domain Generation Algorithms & Fast-Flux',
    what: `Domain Generation Algorithms (DGA) are algorithms embedded in malware that 
automatically generate large numbers of domain names as potential C2 rendezvous points. 
Fast-flux DNS is a technique that rapidly rotates the IP addresses associated with a domain 
to make takedown difficult. Both techniques are used to maintain resilient malware C2 infrastructure.`,
    howWorks: `DGA malware generates hundreds or thousands of domain names daily using 
a seed value (often the current date). Only the attacker knows which domains are actually 
registered — the malware tries each until it finds one that resolves. 
Fast-flux networks use compromised hosts as proxies, changing DNS records every 60–300 seconds 
to create a moving target that is extremely difficult to block.`,
    indicators: [
      'Domains with pseudo-random, algorithmically-generated names',
      'High volume of NXDOMAIN responses followed by a single successful resolution',
      'DNS TTL values of 60 seconds or less (fast-flux indicator)',
      'Single domain resolving to 10+ different IPs within minutes',
      'IP addresses belonging to residential ISPs (compromised proxy hosts)',
      'Domain registration dates matching malware sample compilation dates',
    ],
    report: `Provide the identified domain names, suspected DGA algorithm or family, 
malware samples generating the domains, passive DNS records showing IP rotation, 
and any predicted future domains if the algorithm has been reverse-engineered.`,
    severity: 'CRITICAL',
  },
};

/* ── Show abuse type detail page ─────────────────────────────── */
function showAbuseType(typeId) {
  const d = ABUSE_TYPES[typeId];
  if (!d) return;

  // Hide all pages, show abuse-detail page
  document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
  document.querySelectorAll('.nav-menu a').forEach(a => a.classList.remove('active'));

  const page = document.getElementById('abuse-detail');
  if (!page) return;
  page.classList.add('active');
  window.scrollTo({ top: 0, behavior: 'smooth' });

  const sevColor = d.severity === 'CRITICAL' ? 'var(--red)' : d.severity === 'HIGH' ? 'var(--warn)' : 'var(--accent)';

  page.innerHTML = `
<div class="wrap">
  <div style="margin-bottom:40px">
    <button class="btn btn-g" onclick="nav('home')" style="font-size:10px;padding:8px 18px">
      ← BACK TO HOME
    </button>
  </div>

  <div class="sec-head">
    <div class="sec-tag" style="color:${d.color}">${d.icon} ${d.tag}</div>
    <h2 class="sec-title">${d.title}</h2>
    <div class="sec-rule" style="background:linear-gradient(90deg,${d.color},transparent)"></div>
  </div>

  <!-- Severity badge -->
  <div style="margin-bottom:36px">
    <span style="font-family:var(--mono);font-size:10px;letter-spacing:.2em;
      padding:5px 14px;border:1px solid ${sevColor};color:${sevColor};
      background:${sevColor}22">
      SEVERITY: ${d.severity}
    </span>
  </div>

  <!-- What is it -->
  <div class="abuse-section">
    <div class="abuse-section-title">What is it?</div>
    <p class="abuse-body">${d.what.trim()}</p>
  </div>

  <!-- How it works -->
  <div class="abuse-section">
    <div class="abuse-section-title">How it works</div>
    <p class="abuse-body">${d.howWorks.trim()}</p>
  </div>

  <!-- Indicators -->
  <div class="abuse-section">
    <div class="abuse-section-title">Key Indicators</div>
    <div class="abuse-indicators">
      ${d.indicators.map(i => `
        <div class="abuse-indicator">
          <span class="ai-bullet" style="color:${d.color}">▸</span>
          <span>${i}</span>
        </div>`).join('')}
    </div>
  </div>

  <!-- How to report -->
  <div class="abuse-section">
    <div class="abuse-section-title">How to Report</div>
    <p class="abuse-body">${d.report.trim()}</p>
    <div style="margin-top:24px">
      <button class="btn btn-d" onclick="nav('report')" style="font-size:11px">
        &#9656;&nbsp; SUBMIT ABUSE REPORT
      </button>
    </div>
  </div>

</div>`;
}

/* ── Wire up footer links ────────────────────────────────────── */
window.addEventListener('DOMContentLoaded', () => {
  const map = {
    'Malware / C2':          'malware',
    'Botnet Infrastructure': 'botnet',
    'Phishing Domains':      'phishing',
    'Pharming / DNS Hijack': 'pharming',
    'Snowshoe Spam':         'snowshoe',
    'DGA / Fast-Flux':       'dga',
  };

  document.querySelectorAll('.f-links a').forEach(a => {
    const key = a.textContent.trim();
    if (map[key]) {
      a.style.cursor = 'pointer';
      a.onclick = (e) => { e.preventDefault(); showAbuseType(map[key]); };
    }
  });
});
